<?php
/**
 * Posh Push — wp-config.php snippet
 * AUTO-GENERATED by scripts/configure.js
 *
 * Add the line below to your wp-config.php BEFORE the "That's all, stop editing" line.
 * This tells the plugin which backend server to connect to.
 *
 * The API Key is set once inside WP Admin → Posh Push → Settings — no need to put it here.
 */

define( 'POSH_PUSH_SERVER_URL', 'http://localhost:3000' );
