/**
 * configure.js
 * ============
 * Reads the root .env (or .env.production) and writes the correct
 * environment files for each service:
 *
 *   backend/.env
 *   frontend/.env.local
 *
 * Usage:
 *   node scripts/configure.js                   (uses root .env)
 *   node scripts/configure.js --env .env.production
 *
 * To go live:
 *   1. Edit .env.production with your real URLs and credentials
 *   2. Run:  node scripts/configure.js --env .env.production
 *   3. Restart backend and frontend
 */

const fs = require('fs');
const path = require('path');

// ── Parse arguments ──────────────────────────────────────────────────────────
const args = process.argv.slice(2);
const envFlag = args.indexOf('--env');
const envFile = envFlag !== -1 ? args[envFlag + 1] : '.env';
const ROOT = path.join(__dirname, '..');
const envPath = path.join(ROOT, envFile);

// ── Load and parse the env file ───────────────────────────────────────────────
if (!fs.existsSync(envPath)) {
  console.error(`ERROR: ${envFile} not found. Create it first (copy from .env.production.example).`);
  process.exit(1);
}

const raw = fs.readFileSync(envPath, 'utf8');
const env = {};

raw.split('\n').forEach((line) => {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith('#')) return;
  const eqIdx = trimmed.indexOf('=');
  if (eqIdx === -1) return;
  const key = trimmed.slice(0, eqIdx).trim();
  const val = trimmed.slice(eqIdx + 1).trim();
  env[key] = val;
});

// Resolve ${VAR} references within the file itself
Object.keys(env).forEach((key) => {
  env[key] = env[key].replace(/\$\{([^}]+)\}/g, (_, ref) => env[ref] || '');
});

const get = (key, fallback = '') => env[key] !== undefined ? env[key] : fallback;

// ── Validate required values ──────────────────────────────────────────────────
const required = ['BACKEND_URL', 'FRONTEND_URL', 'DB_HOST', 'JWT_SECRET', 'VAPID_PUBLIC_KEY', 'VAPID_PRIVATE_KEY'];
const missing = required.filter((k) => !get(k));
if (missing.length) {
  console.error('ERROR: Missing required values in ' + envFile + ':');
  missing.forEach((k) => console.error('  ' + k));
  process.exit(1);
}

const BACKEND_URL = get('BACKEND_URL').replace(/\/$/, '');
const FRONTEND_URL = get('FRONTEND_URL').replace(/\/$/, '');
const NODE_ENV = get('NODE_ENV', 'development');

// ── Write backend/.env ────────────────────────────────────────────────────────
const backendEnv = `# AUTO-GENERATED by scripts/configure.js — do not edit manually
# Source: ${envFile}
# Re-generate: node scripts/configure.js${envFile !== '.env' ? ' --env ' + envFile : ''}

NODE_ENV=${NODE_ENV}
PORT=3000
API_PREFIX=api/v1

# Database
DB_TYPE=${get('DB_TYPE', 'mysql')}
DB_HOST=${get('DB_HOST')}
DB_PORT=${get('DB_PORT', '3306')}
DB_USERNAME=${get('DB_USERNAME', 'root')}
DB_PASSWORD=${get('DB_PASSWORD', '')}
DB_NAME=${get('DB_NAME', 'posh_notifications')}

# Auth
JWT_SECRET=${get('JWT_SECRET')}
JWT_EXPIRATION=${get('JWT_EXPIRATION', '7d')}

# CORS — allows frontend and same-origin backend requests
CORS_ORIGINS=${FRONTEND_URL},${BACKEND_URL}

# VAPID keys for web push
VAPID_SUBJECT=${get('VAPID_SUBJECT', 'mailto:admin@poshnotify.com')}
VAPID_PUBLIC_KEY=${get('VAPID_PUBLIC_KEY')}
VAPID_PRIVATE_KEY=${get('VAPID_PRIVATE_KEY')}

# Redis (optional — leave blank to disable queues)
REDIS_HOST=${get('REDIS_HOST', 'localhost')}
REDIS_PORT=${get('REDIS_PORT', '6379')}
REDIS_PASSWORD=${get('REDIS_PASSWORD', '')}

# Rate limiting
THROTTLE_TTL=${get('THROTTLE_TTL', '60')}
THROTTLE_LIMIT=${get('THROTTLE_LIMIT', '100')}

# Super admin
SUPER_ADMIN_EMAIL=${get('SUPER_ADMIN_EMAIL', 'admin@poshnotify.com')}
SUPER_ADMIN_PASSWORD=${get('SUPER_ADMIN_PASSWORD', 'Admin@123456')}

# Frontend URL (used in emails / links)
FRONTEND_URL=${FRONTEND_URL}

# SDK CDN — served from backend /sdk route
SDK_CDN_URL=${BACKEND_URL}/sdk
`;

// ── Write frontend/.env.local ─────────────────────────────────────────────────
const frontendEnv = `# AUTO-GENERATED by scripts/configure.js — do not edit manually
# Source: ${envFile}
# Re-generate: node scripts/configure.js${envFile !== '.env' ? ' --env ' + envFile : ''}

NEXT_PUBLIC_API_URL=${BACKEND_URL}
`;

// ── Save files ────────────────────────────────────────────────────────────────
// ── Write wordpress-plugin/posh-push/wp-config-snippet.php ──────────────────
const wpConfigSnippet = `<?php
/**
 * Posh Push — wp-config.php snippet
 * AUTO-GENERATED by scripts/configure.js
 *
 * Add the line below to your wp-config.php BEFORE the "That's all, stop editing" line.
 * This tells the plugin which backend server to connect to.
 *
 * The API Key is set once inside WP Admin → Posh Push → Settings — no need to put it here.
 */

define( 'POSH_PUSH_SERVER_URL', '${BACKEND_URL}' );
`;

fs.writeFileSync(path.join(ROOT, 'wordpress-plugin', 'posh-push', 'wp-config-snippet.php'), wpConfigSnippet, 'utf8');

fs.writeFileSync(path.join(ROOT, 'backend', '.env'), backendEnv, 'utf8');
fs.writeFileSync(path.join(ROOT, 'frontend', '.env.local'), frontendEnv, 'utf8');

// ── Strip BOM from all plugin PHP files (prevents "unexpected output" on activation) ──
const BOM = Buffer.from([0xEF, 0xBB, 0xBF]);
const pluginDir = path.join(ROOT, 'wordpress-plugin', 'posh-push');
let bomFixed = 0;

function stripBomRecursive(dir) {
  fs.readdirSync(dir).forEach((name) => {
    const full = path.join(dir, name);
    if (fs.statSync(full).isDirectory()) {
      stripBomRecursive(full);
    } else if (name.endsWith('.php')) {
      const buf = fs.readFileSync(full);
      if (buf[0] === 0xEF && buf[1] === 0xBB && buf[2] === 0xBF) {
        fs.writeFileSync(full, buf.slice(3));
        console.log('  ✔  BOM stripped: ' + path.relative(ROOT, full));
        bomFixed++;
      }
    }
  });
}
stripBomRecursive(pluginDir);

console.log('');
console.log('✔  backend/.env                              written');
console.log('✔  frontend/.env.local                       written');
console.log('✔  wordpress-plugin/posh-push/wp-config-snippet.php  written');
if (bomFixed > 0) {
  console.log('✔  ' + bomFixed + ' PHP file(s) had BOM stripped (prevents activation error)');
} else {
  console.log('✔  All PHP files clean (no BOM)');
}
console.log('');
console.log('  Environment : ' + NODE_ENV);
console.log('  Backend URL : ' + BACKEND_URL);
console.log('  Frontend URL: ' + FRONTEND_URL);
console.log('  Database    : ' + get('DB_TYPE') + '://' + get('DB_HOST') + ':' + get('DB_PORT') + '/' + get('DB_NAME'));
console.log('');
console.log('  WordPress setup:');
console.log('  ─────────────────────────────────────────────────────');
console.log('  Step 1 — add ONE line to wp-config.php (before "That\'s all, stop editing"):');
console.log("    define( 'POSH_PUSH_SERVER_URL', '" + BACKEND_URL + "' );");
console.log('  Step 2 — set your API Key once in WP Admin → Posh Push → Settings');
console.log('           (copy it from Dashboard → Sites → API Key — it never changes)');
console.log('  ─────────────────────────────────────────────────────');
console.log('  Full snippet saved to: wordpress-plugin/posh-push/wp-config-snippet.php');
console.log('');
if (NODE_ENV === 'production') {
  console.log('  Restart your backend and frontend servers, then update WordPress.');
} else {
  console.log('  Now run: npm run backend:dev   and   npm run frontend:dev');
}
console.log('');
